CREATE TABLE IF NOT EXISTS EMPLOYEES (
    EMP_ID INTEGER,
    EMP_NAME TEXT,
    DEPARTMENT TEXT,
    SALARY REAL
);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY)
VALUES
(1, 'RITA', 'HR', 35000),
(2, 'JOHN', 'SALES', 42000),
(3, 'DAVID', 'IT', 50000),
(4, 'EMMA', 'HR', 37000),
(5, 'SOPHIA', 'IT', 55000),
(6, 'LIAM', 'SALES', 40000);

SELECT * FROM EMPLOYEES;

SELECT SUM(SALARY) AS Total_Salary
FROM EMPLOYEES;

SELECT AVG(SALARY) AS Average_Salary
FROM EMPLOYEES;

SELECT MIN(SALARY) AS Minimum_Salary
FROM EMPLOYEES;

SELECT MAX(SALARY) AS Maximum_Salary
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT) AS Total_Departments
FROM EMPLOYEES;